const express = require('express')
const app = express()
const port = process.env.PORT || 3000
require('dotenv').config()
require('./connection/db.connection')
const indexRouter = require('./routes/index.router')
const authRouter = require('./routes/auth.router')
const adminRouter = require('./routes/admin.router')
const jwtMiddleware = require('./middlewares/jwt.middleware')
const adminMiddleware = require('./middlewares/admin.middleware')
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(jwtMiddleware)
app.use('/api',indexRouter)
app.use('/api/auth',authRouter)
app.use('/api/admin',adminMiddleware,adminRouter)
app.listen(port,()=>{console.log(`http://localhost:${port}`)})